import { genConfig } from "react-nice-avatar";
export const avatarGenerator = (config) => {
  return { ...genConfig(config) };
};

export const generatedAvatar = () => {
  return [
    {
      sex: "man",
      faceColor: "#F9C9B6",
      earSize: "big",
      eyeStyle: "smile",
      noseStyle: "round",
      mouthStyle: "laugh",
      shirtStyle: "hoody",
      glassesStyle: "none",
      hairColor: "#fff",
      hairStyle: "thick",
      hatStyle: "none",
      hatColor: "#fff",
      eyeBrowStyle: "up",
      shirtColor: "#F4D150",
      bgColor: "#FFEDEF",
    },
    {
      sex: "man",
      faceColor: "#F9C9B6",
      earSize: "big",
      eyeStyle: "smile",
      noseStyle: "round",
      mouthStyle: "peace",
      shirtStyle: "short",
      glassesStyle: "none",
      hairColor: "#000",
      hairStyle: "normal",
      hatStyle: "none",
      hatColor: "#506AF4",
      eyeBrowStyle: "up",
      shirtColor: "#9287FF",
      bgColor: "#E0DDFF",
    },
    {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "big",
      eyeStyle: "smile",
      noseStyle: "short",
      mouthStyle: "peace",
      shirtStyle: "hoody",
      glassesStyle: "none",
      hairColor: "#fff",
      hairStyle: "normal",
      hatStyle: "none",
      hatColor: "#fff",
      eyeBrowStyle: "up",
      shirtColor: "#6BD9E9",
      bgColor: "#FC909F",
    },
    {
      sex: "woman",
      faceColor: "#AC6651",
      earSize: "small",
      eyeStyle: "circle",
      noseStyle: "short",
      mouthStyle: "peace",
      shirtStyle: "polo",
      glassesStyle: "none",
      hairColor: "#000",
      hairStyle: "womanShort",
      hatStyle: "none",
      hatColor: "#000",
      eyeBrowStyle: "upWoman",
      shirtColor: "#77311D",
      bgColor: "#9287FF",
    },
    {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "small",
      eyeStyle: "smile",
      noseStyle: "short",
      mouthStyle: "smile",
      shirtStyle: "polo",
      glassesStyle: "square",
      hairColor: "#506AF4",
      hairStyle: "womanShort",
      hatStyle: "none",
      hatColor: "#506AF4",
      eyeBrowStyle: "upWoman",
      shirtColor: "#6BD9E9",
      bgColor: "#FFEBA4",
    },
    {
      sex: "man",
      faceColor: "#AC6651",
      earSize: "small",
      eyeStyle: "oval",
      noseStyle: "round",
      mouthStyle: "laugh",
      shirtStyle: "short",
      glassesStyle: "none",
      hairColor: "#000",
      hairStyle: "normal",
      hatStyle: "none",
      hatColor: "#fff",
      eyeBrowStyle: "up",
      shirtColor: "#6BD9E9",
      bgColor: "#FFEDEF",
    },
    {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "big",
      eyeStyle: "oval",
      noseStyle: "short",
      mouthStyle: "smile",
      shirtStyle: "polo",
      glassesStyle: "round",
      hairColor: "#000",
      hairStyle: "normal",
      hatStyle: "none",
      hatColor: "#fff",
      eyeBrowStyle: "upWoman",
      shirtColor: "#F4D150",
      bgColor: "#74D153",
    },
    {
      sex: "woman",
      faceColor: "#AC6651",
      earSize: "big",
      eyeStyle: "circle",
      noseStyle: "round",
      mouthStyle: "smile",
      shirtStyle: "hoody",
      glassesStyle: "none",
      hairColor: "#D2EFF3",
      hairStyle: "womanLong",
      hatStyle: "turban",
      hatColor: "#fff",
      eyeBrowStyle: "upWoman",
      shirtColor: "#9287FF",
      bgColor: "#FC909F",
    },
    {
      sex: "woman",
      faceColor: "#AC6651",
      earSize: "small",
      eyeStyle: "circle",
      noseStyle: "short",
      mouthStyle: "laugh",
      shirtStyle: "hoody",
      glassesStyle: "none",
      hairColor: "#D2EFF3",
      hairStyle: "normal",
      hatStyle: "beanie",
      hatColor: "#77311D",
      eyeBrowStyle: "upWoman",
      shirtColor: "#9287FF",
      bgColor: "#FFEDEF",
    },
    {
      sex: "man",
      faceColor: "#AC6651",
      earSize: "small",
      eyeStyle: "oval",
      noseStyle: "long",
      mouthStyle: "laugh",
      shirtStyle: "hoody",
      glassesStyle: "none",
      hairColor: "#000",
      hairStyle: "thick",
      hatStyle: "none",
      hatColor: "#fff",
      eyeBrowStyle: "up",
      shirtColor: "#F4D150",
      bgColor: "#6BD9E9",
    },
  ];
};
